apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: search-proc.workloads.tap.20230518164616.0.0
spec:
  refName: search-proc.workloads.tap
  version: 20230518164616.0.0
  releaseNotes: |
    Release v20230518164616.0.0 of package search-proc.workloads.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: reg.perfect300rock.com/tapdev/supply-chain/search-proc-workloads-bundle@sha256:20f54351a91ca568d058692e06744afa53262c2fcb7e1653540a8fa6680efe0d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

