---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: rabbitmq
spec:
  description:
    short: Amazon MQ/Rabbitmq
  provisioner:
    crossplane:
      compositeResourceDefinition: xrabbitmqbrokers.bindable.database.example.org
