apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrabbitmqbrokers.bindable.database.example.org
spec:
  claimNames:
    kind: RabbitmqBroker
    plural: rabbitmqbrokers
  connectionSecretKeys:
  - type
  - provider
  - host
  - port
  - username
  - password
  group: bindable.database.example.org
  names:
    kind: XRabbitmqBroker
    plural: xrabbitmqbrokers
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              engineVersion:
                type: string
                description: This RMQ Instance engine version
            required:
              - engineVersion

    served: true

