#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: #@ data.values.aws.secmgr.region
      auth:
        jwt:
          serviceAccountRef:
            name: #@ data.values.aws.secmgr.serviceaccount
            namespace: #@ data.values.aws.secmgr.namespace
