---
apiVersion: v1
data:
  database: bXlzcWwtam5iNmg=
  host: MTAuMTAyLjExMy41Mg==
  password: bzB5YWkzUk5YeXZyQkc4YWRnazlUSWZtSEJIZ3VKaEk=
  port: MzMwNg==
  provider: Yml0bmFtaQ==
  type: bXlzcWw=
  username: bXlzcWw=
kind: Secret
metadata:
  name: where-for-dinner-mysql
  namespace: workloads
type: connection.crossplane.io/v1alpha1
---
apiVersion: v1
data:
  host: MTAuMTAwLjEyMS4xMzc=
  password: VG11SEgxOWJPVE9LRkxkdUdDTFk3VjR1bm1WODBXYjg=
  port: NTY3Mg==
  provider: Yml0bmFtaQ==
  type: cmFiYml0bXE=
  username: cmFiYml0bXE=
kind: Secret
metadata:
  name: where-for-dinner-rabbitmq
  namespace: workloads
type: connection.crossplane.io/v1alpha1