---
apiVersion: v1
data:
  database: <db name>
  host: <db host>
  password: <db paswword>
  port: MzMwNg== # 3306
  provider: YXdz  # aws
  type: bXlzcWw=  # mysql
  username: <db username>
kind: Secret
metadata:
  name: where-for-dinner-mysql
type: connection.crossplane.io/v1alpha1
---
apiVersion: v1
data:
  addresses: <broker address including "amqps:" and port>
  password: <broker password>
  provider: YXdz # aws
  type: cmFiYml0bXE= # rabbitmq
  username: <broker username>
kind: Secret
metadata:
  name: where-for-dinner-rabbitmq
type: connection.crossplane.io/v1alpha1