apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcognitocreds.bindable.auth.example.org 
spec:
  claimNames:
    kind: XCognitoCred
    plural: xcognitocreds
  connectionSecretKeys:
  - type
  - provider
  - authorization-grant-types
  - client-authentication-method
  - client-id
  - client-secret
  - issuer-uri
  - scope  
  group: bindable.auth.example.org 
  names:
    kind: XCognitoCred
    plural: xcognitocreds
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: XRD for generating a service bindable secret for pre-provisioned AWS Cognito instances.
            properties:
              secretName:
                description: The name of AWS secret stored in AWS Secret Manager
                type: string 
            required:
            - secretName                              
            type: object
        type: object    
    served: true
