---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: where-for-dinner-ui
spec:
 serviceAccountName: server-workload-installer  
 packageRef:
   refName: where-for-dinner-ui.default.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: where-for-dinner-ui-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: where-for-dinner-ui-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: where-for-dinner-ui