---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: "aws"
  name: xspringcloudgateways.gateway.example.org 
spec:
  compositeTypeRef:
    apiVersion: gateway.example.org/v1alpha1  
    kind: XSpringCloudGateway
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      name: external-secret
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
                namespace: ""
            spec:
              secretStoreRef:
                name: aws-secretsmanager
                kind: ClusterSecretStore 
              target:
                template:
                  data:    
                    authorization-grant-types: "{{ .authorizationgranttypes }}"
                    client-authentication-method : "{{ .clientauthenticationmethod }}"
                    client-id: "{{ .clientid }}"     
                    client-secret: "{{ .clientsecret }}"                        
                    issuer-uri : "{{ .issueruri }}"      
                    scope: "{{ .scope }}"                                                     
              dataFrom:
              - extract:
                  conversionStrategy: Default            
    patches:  
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath          
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
      - fromFieldPath: spec.secretName
        toFieldPath: spec.forProvider.manifest.spec.dataFrom[0].extract.key
  - base:
      name: external-secret
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: tanzu.vmware.com/v1
            kind: SpringCloudGateway
            metadata:
              namespace: ""
            spec:
              service:
                type: ClusterIP  
              api:
                title: Where For Dinner API Gateway
                description: Where For Dinner APIs for creating searches and retrieving search results.
                version: 1.0.0
              env:
                - name: spring.cloud.gateway.httpclient.connect-timeout
                  value: "90"
              sso:
                secret: ""
    patches:  
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath          
      - fromFieldPath: spec.gatewayName
        toFieldPath: spec.forProvider.manifest.metadata.name
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.spec.sso.secret