---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: rds-creds
spec:
  description:
    short: AWS RDS Credentials
  provisioner:
    crossplane:
      compositeResourceDefinition: xrdscreds.bindable.database.example.org
