---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: where-for-dinner-availability
spec:
 serviceAccountName: default
 packageRef:
   refName: availability.default.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: where-for-dinner-availability-package-values # Secret created in previous step