---
apiVersion: v1
kind: Secret
metadata:
 name: where-for-dinner-search-proc-package-values
stringData:
 values.yaml: |
   ---
   replicas: 2
   hostname: ""
   workload_name: where-for-dinner-search-proc