---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: where-for-dinner-search-proc
spec:
 serviceAccountName: default
 packageRef:
   refName: search-proc.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: where-for-dinner-search-proc-package-values # Secret created in previous step