---
apiVersion: v1
kind: Secret
metadata:
 name: where-for-dinner-availability-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: where-for-dinner-availability