apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xspringcloudgateways.gateway.example.org 
spec:
  claimNames:
    kind: XSpringCloudGateway
    plural: xspringcloudgateways
  group: gateway.example.org 
  names:
    kind: XSpringCloudGateway
    plural: xspringcloudgateways
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: XRD for generating a Spring Cloud Gateway along with a secret backed by a pre-provisioned AWS Cognito instance.
            properties:
              secretName:
                description: The name of AWS secret stored in AWS Secret Manager that holds the SSO/Cognito information
                type: string 
              gatewayName:
                description: The name of the Spring Cloud Gateway instance that will be created
                type: string 
            required:
            - secretName 
            - gatewayName                             
            type: object
        type: object    
    served: true
