apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-crawler
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/gm2552/where-for-dinner-northstar
      ref:
        branch: main
    subPath: where-for-dinner-crawler-python