apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-proc
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: where-for-dinner-search-proc
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  env:
  - name: spring_profiles_active
    value: redis,crawler,rabbitmq
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: msgbroker-where-for-dinner
  - name: cache
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: cache-where-for-dinner
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/gm2552/where-for-dinner-northstar
      ref:
        branch: main
    subPath: where-for-dinner-search-proc