---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: elaticache-cred
spec:
  description:
    short: Elasticache/Redis Credentials
  provisioner:
    crossplane:
      compositeResourceDefinition: xredisclusterscreds.bindable.cache.example.org 
