apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: search-proc
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: search-proc
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
spec:
  env:
  - name: spring_profiles_active
    value: crawler,rabbitmq
# Rabbit MQ settings
  - name: spring_rabbitmq_addresses
    valueFrom:
      secretKeyRef:
        name: where-for-dinner-rabbitmq
        key: addresses
  - name: spring_rabbitmq_username
    valueFrom:
      secretKeyRef:
        name: where-for-dinner-rabbitmq
        key: username   
  - name: spring_rabbitmq_password
    valueFrom:
      secretKeyRef:
        name: where-for-dinner-rabbitmq
        key: password      
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: 1500m
  source:
    git:
      url: https://github.com/gm2552/where-for-dinner-northstar
      ref:
        branch: main
    subPath: where-for-dinner-search-proc