apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.workloads.tap.20230515151453.0.0
spec:
  refName: where-for-dinner-search.workloads.tap
  version: 20230515151453.0.0
  releaseNotes: |
    Release v20230515151453.0.0 of package where-for-dinner-search.workloads.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: reg.perfect300rock.com/tapdev/supply-chain/where-for-dinner-search-workloads-bundle@sha256:a70b705e4501d42f4661c7e031afb712a26cb9a1c4186d527a54d35ad3dc7c5b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

