apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.workloads.tap.20230518164617.0.0
spec:
  refName: where-for-dinner-search.workloads.tap
  version: 20230518164617.0.0
  releaseNotes: |
    Release v20230518164617.0.0 of package where-for-dinner-search.workloads.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: reg.perfect300rock.com/tapdev/supply-chain/where-for-dinner-search-workloads-bundle@sha256:4621411e4e232dd1c59cb4af4508d784035153d9febe32a520fc9c1504be4b94
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

