---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: "aws"
  name: xcognitocreds.bindable.auth.example.org 
spec:
  compositeTypeRef:
    apiVersion: bindable.auth.example.org/v1alpha1  
    kind: XCognitoCred
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      type: FromCompositeFieldPath
  - base:
      name: external-secret
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
                namespace: ""
            spec:
              secretStoreRef:
                name: aws-secretsmanager
                kind: ClusterSecretStore 
              target:
                template:
                  type: servicebinding.io/config
                  data:    
                    authorizationgranttypes: "{{ .authorizationgranttypes }}"
                    clientauthenticationmethod: "{{ .clientauthenticationmethod }}"
                    clientid: "{{ .clientid }}"     
                    clientsecret: "{{ .clientsecret }}"                        
                    issueruri: "{{ .issueruri }}"      
                    scope: "{{ .scope }}"                                                     
              dataFrom:
              - extract:
                  conversionStrategy: Default
        writeConnectionSecretToRef:
          namespace: crossplane-system        
        connectionDetails:
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.authorizationgranttypes
          toConnectionSecretKey: authorization-grant-types
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.clientauthenticationmethod
          toConnectionSecretKey: client-authentication-method
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.clientid
          toConnectionSecretKey: client-id
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.clientsecret
          toConnectionSecretKey: client-secret        
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.issueruri
          toConnectionSecretKey: issuer-uri                                
        - apiVersion: v1
          kind: Secret
          namespace: ""
          fieldPath: data.scope
          toConnectionSecretKey: scope             
    connectionDetails:
    - name: type
      value: oauth2
    - name: provider
      value: aws
    - fromConnectionSecretKey: authorization-grant-types     
      name: authorization-grant-types
    - fromConnectionSecretKey: client-authentication-method
      name: client-authentication-method      
    - fromConnectionSecretKey: client-id
      name: client-id
    - fromConnectionSecretKey: client-secret
      name: client-secret
    - fromConnectionSecretKey: issuer-uri
      name: issuer-uri    
    - fromConnectionSecretKey: scope
      name: scope                    
    patches:  
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: metadata.uid
        toFieldPath: spec.writeConnectionSecretToRef.name
        transforms:
        - string:
            fmt: '%s-elaticache'
            type: Format
          type: string
        type: FromCompositeFieldPath        
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
      - fromFieldPath: spec.secretName
        toFieldPath: spec.forProvider.manifest.spec.dataFrom[0].extract.key
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[0].name
        type: FromCompositeFieldPath     
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[1].name
        type: FromCompositeFieldPath   
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[2].name
        type: FromCompositeFieldPath  
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[3].name
        type: FromCompositeFieldPath       
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[4].name
        type: FromCompositeFieldPath      
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[5].name
        type: FromCompositeFieldPath                  
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[0].namespace
        type: FromCompositeFieldPath     
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[1].namespace
        type: FromCompositeFieldPath   
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[2].namespace
        type: FromCompositeFieldPath  
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[3].namespace
        type: FromCompositeFieldPath          
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[4].namespace
        type: FromCompositeFieldPath           
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[5].namespace
        type: FromCompositeFieldPath              